// <auto-generated />
namespace Azure.TestProject.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class auditable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(auditable));
        
        string IMigrationMetadata.Id
        {
            get { return "202002130430375_auditable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
